name: project
description: A new Flutter project.

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=2.18.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  animated_splash_screen: ^1.3.0
  intl: ^0.18.0
  firebase_core: ^2.9.0
  firebase_auth: ^4.4.0
  cloud_firestore: ^4.5.1
  lottie: ^2.3.1
  get: ^4.6.5
  image_picker: ^1.0.0
  camera: ^0.10.5+2
  file_picker: ^5.2.5
  carousel_slider: ^4.2.1
  firebase_storage: ^11.2.1
  flutter_svg: 
  fluttertoast: ^8.2.1
  geekyants_flutter_gauges: ^1.0.1
  syncfusion_flutter_gauges: ^22.1.37
  provider: ^6.0.5
  pdf: ^3.6.0
  syncfusion_flutter_pdf: ^22.1.37
  path_provider: ^2.0.15
  google_nav_bar: ^5.0.6
  persistent_bottom_nav_bar: ^5.0.2
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.11.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/play_store_512.png"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/play_store_512.png"
    background_color: "#bd08bd"
    theme_color: "#bd08bd"
  windows:
    generate: true
    image_path: "assets/play_store_512.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/play_store_512.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: Raleway
      fonts:
      - asset: assets/fonts/Raleway-Regular.ttf
      - asset: assets/fonts/Raleway-Italic.ttf
        style: italic
    - family: RobotoMono
      fonts:
      - asset: assets/fonts/RobotoMono-Regular.ttf
      - asset: assets/fonts/RobotoMono-Bold.ttf
    - family: Oswald
      fonts:
      - asset: assets/fonts/Oswald-Regular.ttf
      - asset: assets/fonts/Oswald-Bold.ttf
    - family : Pacifico
      fonts:
      - asset: assets/fonts/Pacifico-Regular.ttf
        weight: 700
