// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDKXpGJXePoCBo3wudJ_E7JgYoQ7FBTOdM',
    appId: '1:118966819353:web:6fffc3eea7f66300f8e888',
    messagingSenderId: '118966819353',
    projectId: 'project-5e9dd',
    authDomain: 'project-5e9dd.firebaseapp.com',
    storageBucket: 'project-5e9dd.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCAUMngqnaafAe8o3ajFJvSkb_YZNPXG1M',
    appId: '1:118966819353:android:23c0962dbcd98249f8e888',
    messagingSenderId: '118966819353',
    projectId: 'project-5e9dd',
    storageBucket: 'project-5e9dd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB786mEV26yhVnYTS4XlHkyEcArABJUdKE',
    appId: '1:118966819353:ios:55e4c014ad95078ef8e888',
    messagingSenderId: '118966819353',
    projectId: 'project-5e9dd',
    storageBucket: 'project-5e9dd.appspot.com',
    iosClientId: '118966819353-chk59n3v101ccjd67tr18os4mur41q7d.apps.googleusercontent.com',
    iosBundleId: 'com.example.project',
  );
}
